//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.TextBlasts = new HashSet<TextBlast>();
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int GroupID { get; set; }
        public string Name { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual ICollection<TextBlast> TextBlasts { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
