//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mother
    {
        public int MotherID { get; set; }
        public string BabyFirstName { get; set; }
        public string BabyLastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
