//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.TextBlasts = new HashSet<TextBlast>();
            this.Sessions = new HashSet<Session>();
        }
    
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual Mother Mother { get; set; }
        public virtual ICollection<TextBlast> TextBlasts { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
