//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person
    {
        public Person()
        {
            this.TextBlasts = new HashSet<TextBlast>();
            this.Sessions = new HashSet<Session>();
            this.ForumPosts = new HashSet<ForumPost>();
            this.ForumThreads = new HashSet<ForumThread>();
            this.GroupMembers = new HashSet<GroupMember>();
            this.Messages = new HashSet<Message>();
            this.MessageThreads = new HashSet<MessageThread>();
            this.MessageThreads1 = new HashSet<MessageThread>();
            this.TextFieldResponses = new HashSet<TextFieldResponse>();
        }
    
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Type { get; set; }
        [Required(ErrorMessage = "Please Provide Username", AllowEmptyStrings = false)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        public string GCMConnectionString { get; set; }
    
        public virtual Mother Mother { get; set; }
        public virtual ICollection<TextBlast> TextBlasts { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<ForumPost> ForumPosts { get; set; }
        public virtual ICollection<ForumThread> ForumThreads { get; set; }
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageThread> MessageThreads { get; set; }
        public virtual ICollection<MessageThread> MessageThreads1 { get; set; }
        public virtual ICollection<TextFieldResponse> TextFieldResponses { get; set; }
    }
}
