//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextBlast
    {
        public TextBlast()
        {
            this.TextViews = new HashSet<TextView>();
            this.TextFields = new HashSet<TextField>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int TextBlastID { get; set; }
        public string Title { get; set; }
        public int Creator { get; set; }
        public int GroupID { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<TextView> TextViews { get; set; }
        public virtual ICollection<TextField> TextFields { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
