//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextField
    {
        public TextField()
        {
            this.TextFieldResponses = new HashSet<TextFieldResponse>();
        }
    
        public int TextFieldID { get; set; }
        public int TextBlastID { get; set; }
    
        public virtual TextBlast TextBlast { get; set; }
        public virtual ICollection<TextFieldResponse> TextFieldResponses { get; set; }
    }
}
