//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextView
    {
        public int TextViewID { get; set; }
        public string Text { get; set; }
        public int TextBlastID { get; set; }
    
        public virtual TextBlast TextBlast { get; set; }
    }
}
